### The Ultimate Water System
# written by Kjell

esphome:
  name: watersysteem
  friendly_name: Watersysteem

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BoEliEKdwduVeAiNUockde0/TeNXvJCees77YDFz7jA="

ota:
  - platform: esphome
    password: "c50539ee1af9e506b6007999eb8f6d14"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Watersysteem Fallback Hotspot"
    password: "V2dJKfdCVYAC"

captive_portal:
    
# Enable basic web server for easy debugging
web_server:
  port: 80
  version: 3

# Setup I2C for communication
i2c:
  sda: GPIO18
  scl: GPIO17
  scan: True

### IO EXPANDER ###
mcp23017:
  - id: 'expander'
    address: 0x27

### ADC ###
ads1115:
  - address: 0x49


# OUTPUTS
switch:
  # ONBOARD LED
  - platform: gpio
    name: "Onboard LED"
    pin: GPIO2
  # WATER LED
  - platform: gpio
    name: "Status LED Rood"
    inverted: True
    pin:
      mcp23xxx: expander
      number: 7 #A7
      mode:
        output: True
  # NUTRIENTS LED
  - platform: gpio
    name: "Status LED Geel"
    inverted: True
    pin:
      mcp23xxx: expander
      number: 8 #B0
      mode:
        output: True
  # RELAYS
  - platform: gpio
    name: "Relais Mixer"
    pin:
      mcp23xxx: expander
      number: 0 #A0
      mode:
        output: True
  - platform: gpio
    name: "Relais UV lamp"
    pin:
      mcp23xxx: expander
      number: 1 #A1
      mode:
        output: True
  - platform: gpio
    name: "Luchtpomp"
    pin:
      mcp23xxx: expander
      number: 2 #A2
      mode:
        output: True
  - platform: gpio
    name: "Pomp bak links"
    pin:
      mcp23xxx: expander
      number: 6 #A6
      mode:
        output: True
  - platform: gpio
    name: "Pomp bak midden"
    pin:
      mcp23xxx: expander
      number: 5 #A5
      mode:
        output: True
  - platform: gpio
    name: "Pomp lade voorkant"
    pin:
      mcp23xxx: expander
      number: 4 #A4
      mode:
        output: True
  - platform: gpio
    name: "Pomp lade achterkant"
    pin:
      mcp23xxx: expander
      number: 3 #A3
      mode:
        output: True


# INPUTS
sensor:
  # HEIGHT SENSORS (ULTRASONIC)
  - platform: ultrasonic
    name: "Hoogte Nutriënten"
    trigger_pin: GPIO26
    echo_pin: GPIO25
    update_interval: 1s
  - platform: ultrasonic
    name: "Hoogte Water"
    trigger_pin: GPIO33
    echo_pin: GPIO32
    update_interval: 1s
  - platform: ultrasonic
    name: "Hoogte mixer"
    trigger_pin: GPIO14
    echo_pin: GPIO27
    update_interval: 1s
  # ANALOG PROBES
  - platform: ads1115
    name: "Kalium Nutriënten" # Nutriënten 1
    multiplexer: A2_A3
    gain: 0.256 # meausures up to 0.256V (see documentation)
    update_interval: 5s
    filters: # y=0.0138ln(x)+0,0196
      - lambda: |-
          return exp((x - 0.0196) / 0.0138);
    unit_of_measurement: "g/l"
  - platform: ads1115
    name: "Calcium Nutriënten" # Nutriënten 2
    multiplexer: A1_A3
    gain: 0.256
    update_interval: 5s
    filters: # y=0.0087ln(x)-0.0079
      - lambda: |-
          return exp((x + 0.0079) / 0.0087);
    unit_of_measurement: "g/l"
  #- platform: ads1115
  #  name: "Nutriënten 3" # Nutriënten 3
  #  multiplexer: A0_A3
  #  gain: 0.256
  #  update_interval: 5s
  # CURRENT SENSOR (FOR POWER CONSUMPTION)
  - platform: adc
    name: "Vermogenverbruik"
    pin: GPIO35
    update_interval: 1s
    samples: 5
    attenuation: 11db # change range to 0-3.9V
    filters: # linear regression: I = (V - 2.3363) / 0.1608
      - clamp:
          min_value: 2.34
      - offset: -2.3363
      - multiply: 6.2189
      # Multiply by voltage to get power consumption
      - multiply: 12
    unit_of_measurement: "W"
          
binary_sensor:
  # LIMIT SWITCHES
  - platform: gpio
    name: "Eindeloopschakelaar 1"
    pin:
      mcp23xxx: expander
      number: 9 #B1
      mode:
        input: True
        pullup: False
  - platform: gpio
    name: "Eindeloopschakelaar 2"
    pin:
      mcp23xxx: expander
      number: 10 #B2
      mode:
        input: True
        pullup: False
  - platform: gpio
    name: "Eindeloopschakelaar 3"
    pin:
      mcp23xxx: expander
      number: 11 #B3
      mode:
        input: True
        pullup: False