esphome:
  name: plantenbak
  friendly_name: Plantenbak

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "2L+Wt0g5izMqUAleHCo1f2ePfl7o5CjlzmpNRwCA5nY="

ota:
  - platform: esphome
    password: "5777794c3bacfee064b0f15a4e39dea2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plantenbak Fallback Hotspot"
    password: "na05gv8dfHVP"

# I2C Configuratie (wordt gedeeld door zowel PN532 als SCD4x)
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true  # Automatische detectie van I2C-apparaten

# PN532 RFID Configuratie
pn532_i2c:
  id: pn532_board
  on_tag:
    then:
      - lambda: |-
          // Verkrijg de UID van de gescande tag
          std::vector<unsigned char> tag_uid = tag.get_uid();
          // Zet de UID om naar een string van hex-waarden
          char uid_str[33]; // Maximum 32 bytes + null terminator
          for (size_t i = 0; i < tag_uid.size(); ++i) {
            snprintf(uid_str + i * 2, 3, "%02X", tag_uid[i]);
          }
          ESP_LOGD("rfid", "UID gescand: %s", uid_str);

          // Maak een mapping van UID naar plantnaam
          std::map<std::string, std::string> uid_to_plant = {
            {"49FFE4C2", "Paprika"},
            {"D3FD8D03", "Sla"},
            {"A378940C", "Tomaat"}
          };

          // Zoek de plantnaam op basis van de UID
          std::string plant_name = "Onbekend";  // Standaardwaarde
          if (uid_to_plant.find(uid_str) != uid_to_plant.end()) {
            plant_name = uid_to_plant[uid_str]; // Haal de plantnaam op
          }

          // Log de plantnaam
          ESP_LOGD("rfid", "Gekoppelde plantnaam: %s", plant_name.c_str());

          // Stuur de plantnaam naar Home Assistant
          id(rfid_uid_sensor).publish_state(plant_name);

# RFID UID als tekstsensor naar Home Assistant sturen
text_sensor:
  - platform: template
    name: "RFID UID"
    id: rfid_uid_sensor

  - platform: version
    name: "ESPHome Versie"
  

sensor:
  - platform: scd4x
    co2:
      name: "CO2 Niveau"
      accuracy_decimals: 0
      unit_of_measurement: "ppm"
    temperature:
      name: "Temperatuur"
      accuracy_decimals: 1
      unit_of_measurement: "°C"
    humidity:
      name: "Luchtvochtigheid"
      accuracy_decimals: 1
      unit_of_measurement: "%"
    automatic_self_calibration: true  # Automatische kalibratie inschakelen
    update_interval: 2s


  - platform: adc
    pin: GPIO32
    id: "adcMoisture1"
    accuracy_decimals: 3
    unit_of_measurement: '%'
    attenuation: 11db
    filters:
      - calibrate_linear:
        - 1.111  -> 100.0
        - 2.52 -> 0
      - lambda: if (x < 0) return 0; else if (x > 100) return 100; else return (x);
    name: "Soil-Moister Links"
    update_interval: 2s
    force_update: true

  - platform: adc
    pin: GPIO34
    id: "adcMoisture2"
    accuracy_decimals: 3
    unit_of_measurement: '%'
    attenuation: 11db
    filters:
      - calibrate_linear:
        - 1.111  -> 100.0
        - 2.52 -> 0
      - lambda: if (x < 0) return 0; else if (x > 100) return 100; else return (x);
    name: "Soil-Moister Rechts"
    update_interval: 2s
    force_update: true


  - platform: adc
    pin: GPIO33
    id: "adcCurrent"
    accuracy_decimals: 3
    unit_of_measurement: 'A'
    attenuation: 11db
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0   # Pas deze waarden aan afhankelijk van de stroommeter
          - 3.3 -> 10.0  # Voorbeeld: 3.3V = 10A (pas aan op basis van je sensor)
      - lambda: if (x < 0) return 0; else return (x);  # Negatieve waarden voorkomen
    name: "Stroomverbruik"
    update_interval: 1s
    force_update: true
